### ISSUE TITLE
Items don't appear when I set empty ArrayList for the first time using setData()

### ISSUE THREAD

**Issue by namhnz** [thesurix/gesture-recycler#9]
After setting mAdapter.setData(new ArrayList<>()) - empty ArrayList for the first time, any item I insert then doesn't appear in RecyclerView. But if I use mAdapter.setData( [new ArrayList with item(s)] ), all items inserted then appear normally. How can I fix this?

**Comment by thesurix** [comment]
Could you show sample code with `mAdapter.setData(new ArrayList<>())`? If you want to insert items you can use `public void insert(final T item, final int position)` method.

**Comment by buithehien1991** [comment]
@thesurix For example, when we make list items from Internet (asynchronuous), so first time need set empty, after get new list items, we set again. But no have new data disply on UI. 

Edited:
I pushed adapter.setData(items); at to main UI thread and it run OK. Thank you

**Comment by namhnz** [comment]
@buithehien1991 That is right. I'm using firebase for adding new items, in childAdded method of onChildValueListener event.
@thesurix Method setData, insert, remove don't work when I put it in childAdded() if the first time setData() to empty list. It is still work if the list has at least one item.

Thank you all for the replies.

**Comment by thesurix** [comment]
@namhnz Are you sure that `setData` is called on main thread (UI)?

**Comment by namhnz** [comment]
@thesurix I tried to run setData on the main thread (I used a method here: https://stackoverflow.com/questions/13746940/android-calling-ui-thread-from-worker-thread)
but it still doesn't work.
In Logcat I found **E/RecyclerView: No adapter attached; skipping layout** both circumstances, but only when setData(**not empty list**) it works.

This is my source code:
`
public class LinksRecyclerFragment extends Fragment {

    private final int NUM_LINK_PER_PAGE = 10;

    FirebaseAuth mAuth;
    DatabaseReference mDataDeviceDatabase;

    private String mUserUid;
    private String mDeviceKey;

    //For load 10 item from Firebase
    private int mItemLoadPos = 0;
    private String mEndForNextLoadKey = "";
    private String mPreviousEndForNextLoadKey = "";

    //Window
    private RecyclerView mRecyclerView;
    private GestureManager mGestureManager;
    private LinksAdapter mAdapter;


    public LinksRecyclerFragment() {
        // Required empty public constructor
    }

    @Nullable
    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, @Nullable ViewGroup container, @Nullable Bundle savedInstanceState) {
        mAuth = FirebaseAuth.getInstance();
        mUserUid = mAuth.getCurrentUser().getUid();


        View rootView = inflater.inflate(R.layout.fragment_links_recycler, container, false);
        mRecyclerView = rootView.findViewById(R.id.links_recycler_view);


        return rootView;
    }

    @Override
    public void onViewCreated(@NonNull View view, @Nullable Bundle savedInstanceState) {
        super.onViewCreated(view, savedInstanceState);

        findDeviceDataKey();


    }


    private void findDeviceDataKey(){
        final String thisDeviceInstanceId = FirebaseInstanceId.getInstance().getToken();

        Query thisDeviceDatabase = FirebaseDatabase.getInstance().getReference().child("Devices").child(mUserUid)
                .orderByChild("instance_id").equalTo(thisDeviceInstanceId);

        thisDeviceDatabase.addListenerForSingleValueEvent(new ValueEventListener() {
            @Override
            public void onDataChange(DataSnapshot dataSnapshot) {
                if(dataSnapshot.exists()){
                    for (DataSnapshot devicePushedId : dataSnapshot.getChildren()){
                        mDeviceKey = devicePushedId.getKey(); // The query just returns one result so dataSnapshot has only one child
                    }
                    Log.d("DATA_DEVICE_KEY", mDeviceKey);

                    mDataDeviceDatabase = FirebaseDatabase.getInstance().getReference().child("Data").child(mUserUid).child(mDeviceKey);

                    mapControls(getView());

                }
            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });
    }



    private void mapControls(View rootView) {

        LinearLayoutManager layoutManager = new LinearLayoutManager(getContext());
        mRecyclerView.setHasFixedSize(true);
        mRecyclerView.setLayoutManager(layoutManager);

        mAdapter = new LinksAdapter(getContext(), R.layout.link_item);
        mAdapter.setData(getInitialLink());

        mAdapter.setDataChangeListener(new GestureAdapter.OnDataChangeListener<LinkItem>() {
            @Override
            public void onItemRemoved(LinkItem item, int position) {
                performActionDelete(item);
            }

            @Override
            public void onItemReorder(LinkItem item, int fromPos, int toPos) {

            }
        });

        View emptyView = rootView.findViewById(R.id.links_empty_root);
        mAdapter.setEmptyView(emptyView);



        mRecyclerView.setAdapter(mAdapter);

        mRecyclerView.addOnItemTouchListener(new RecyclerItemTouchListener<>(new DefaultItemClickListener<LinkItem>(){
            @Override
            public boolean onItemClick(LinkItem item, int position) {
                performActionCopy(getContext(), item.getUrl());
                return true;
            }

            @Override
            public boolean onDoubleTap(LinkItem item, int position) {
                performActionOpen(getContext(), item.getUrl());
                return true;
            }

            @Override
            public void onItemLongPress(LinkItem item, int position) {
                showCommandsDialog(item);
            }
        }));

        mGestureManager = new GestureManager.Builder(mRecyclerView)
                .setSwipeEnabled(true)
                .setSwipeFlags(ItemTouchHelper.LEFT | ItemTouchHelper.RIGHT)
                .build();



        EndlessRecyclerViewScrollListener scrollListener = new EndlessRecyclerViewScrollListener(layoutManager) {
            @Override
            public void onLoadMore(int page, int totalItemsCount, RecyclerView view) {

                loadMoreData(totalItemsCount);

            }
        };

        mRecyclerView.addOnScrollListener(scrollListener);

        initialData();

    }

    private void showCommandsDialog(LinkItem item) {
        AlertDialog.Builder dialogBuilder = new AlertDialog.Builder(getContext());
        LayoutInflater inflater = this.getLayoutInflater();
        View dialogView = inflater.inflate(R.layout.recycler_commands_dialog, null);
        dialogBuilder.setView(dialogView);
        dialogBuilder.setTitle("Choose Action");

        Button mCopyBtn = dialogView.findViewById(R.id.recycler_commands_dialog_copy_btn);
        Button mOpenBtn = dialogView.findViewById(R.id.recycler_commands_dialog_open_btn);
        Button mDeleteBtn = dialogView.findViewById(R.id.recycler_commands_dialog_delete_btn);


        AlertDialog alertDialog = dialogBuilder.create();

        mCopyBtn.setOnClickListener(v -> {
            performActionCopy(getContext(), item.getUrl());
            alertDialog.dismiss();
        });

        mOpenBtn.setOnClickListener(v -> {
            performActionOpen(getContext(), item.getUrl());
            alertDialog.dismiss();
        });

        mDeleteBtn.setOnClickListener(v -> {
            performActionDelete(item);
            alertDialog.dismiss();
        });

        alertDialog.show();
    }




    private void initialData(){
        Log.d("LOAD_DATA_LINK", "initialData");


        Query linksDataQuery = mDataDeviceDatabase.orderByKey().limitToLast(NUM_LINK_PER_PAGE); //Load first NUM_LINK_PER_PAGE item

        linksDataQuery.addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(DataSnapshot dataSnapshot, String s) {
                LinkItem link = dataSnapshot.getValue(LinkItem.class);
                String linkKey = dataSnapshot.getKey();
                link.setKey(linkKey);

                if(mItemLoadPos == 0){
                    mEndForNextLoadKey = linkKey;
                    mPreviousEndForNextLoadKey = linkKey;
                }

                mItemLoadPos++;

                mAdapter.insert(link, 0);

                if (mItemLoadPos == 1){
                    mAdapter.remove(1); //Remove initial item
                }

                Log.d("LINK_ITEM_ADDED", link.getUrl() + "/" + String.valueOf(link.getLocalTime()));

                Log.d("LOAD_LINKS", "mEndForNextLoadKey:" + mEndForNextLoadKey + "/mPreviousEndForNextLoadKey:" + mPreviousEndForNextLoadKey);

                mRecyclerView.scrollToPosition(0);
            }

            @Override
            public void onChildChanged(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onChildRemoved(DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });
    }


    private void loadMoreData(final int posToAddNewLinks){
        Log.d("LOAD_DATA_LINK", "loadMoreData");

        mItemLoadPos = 0;

        Query linksDataQuery = mDataDeviceDatabase.orderByKey().endAt(mEndForNextLoadKey).limitToLast(NUM_LINK_PER_PAGE + 1); //Duplicate last item

        linksDataQuery.addChildEventListener(new ChildEventListener() {
            @Override
            public void onChildAdded(DataSnapshot dataSnapshot, String s) {
                LinkItem link = dataSnapshot.getValue(LinkItem.class);
                String linkKey = dataSnapshot.getKey();
                link.setKey(linkKey);

                if(mItemLoadPos == 0){
                    mEndForNextLoadKey = linkKey;
                }

                if(!mPreviousEndForNextLoadKey.equals(linkKey)){
                    mItemLoadPos++;
                    mAdapter.insert(link, posToAddNewLinks);
                } else { //End of loading new item
                    mPreviousEndForNextLoadKey = mEndForNextLoadKey;

                    Log.d("LINK_ITEM_ADDED", link.getUrl() + "/" + String.valueOf(link.getLocalTime()));
                }

                Log.d("LOAD_LINKS", "mEndForNextLoadKey:" + mEndForNextLoadKey + "/mPreviousEndForNextLoadKey:" + mPreviousEndForNextLoadKey);

            }

            @Override
            public void onChildChanged(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onChildRemoved(DataSnapshot dataSnapshot) {

            }

            @Override
            public void onChildMoved(DataSnapshot dataSnapshot, String s) {

            }

            @Override
            public void onCancelled(DatabaseError databaseError) {

            }
        });
    }

    public void performActionOpen(Context context, String url){
        Log.d("RECYCLER_VIEW_ACTION", "open" + url);

        Intent browserIntent = new Intent(Intent.ACTION_VIEW, Uri.parse(url));
        context.startActivity(browserIntent);
    }

    public void performActionCopy(Context context, String url){
        Log.d("RECYCLER_VIEW_ACTION", "copy" + url);

        ClipboardManager clipboard = (ClipboardManager) context.getSystemService(Context
                .CLIPBOARD_SERVICE);
        ClipData clip = ClipData.newPlainText("Send To Phone copied the link from RecyclerView", url);
        clipboard.setPrimaryClip(clip);

        Toast.makeText(context, "Link is copied", Toast.LENGTH_SHORT).show();

    }

    private void performActionDelete(LinkItem item) {
        Log.d("RECYCLER_VIEW_ACTION", "delete");

        mDataDeviceDatabase.child(item.getKey()).removeValue((databaseError, databaseReference) -> {
            if(databaseError == null)
                Toast.makeText(getContext(), "Link is deleted", Toast.LENGTH_SHORT).show();
            else
            {
                Log.d("FIREBASE_DELETE_LINK", databaseError.getMessage());
                Toast.makeText(getContext(), "Can't delete the link, please try again later", Toast.LENGTH_SHORT).show();
                mAdapter.undoLast();
            }
        });
    }


    protected List<LinkItem> getInitialLink() {
        final List<LinkItem> linkItemList = new ArrayList<>();
        linkItemList.add(new LinkItem());
        return linkItemList;
    }


}
`

**Comment by namhnz** [comment]
And this is my Adapter:

`
public class LinksAdapter extends GestureAdapter<LinkItem, GestureViewHolder> {

    private final Context mCtx;
    private int mItemResId;


    public LinksAdapter(Context mCtx, int mItemResId) {
        this.mCtx = mCtx;
        this.mItemResId = mItemResId;
    }

    @NonNull
    @Override
    public GestureViewHolder onCreateViewHolder(@NonNull ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext()).inflate(mItemResId, parent, false);
        return new LinkViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(GestureViewHolder holder, int position) {
        super.onBindViewHolder(holder, position);
        final LinkItem linkItem = getItem(position);

        LinkViewHolder linkViewHolder = (LinkViewHolder) holder;
        linkViewHolder.mLinkHostText.setText(linkItem.getHost());



        linkViewHolder.mLinkTimeText.setText(DateUtils.getRelativeTimeSpanString(linkItem.getLocalTime(), System.currentTimeMillis(), 0L));

        linkViewHolder.mLinkDataText.setText(linkItem.getUrl());
    }
}
`

**Comment by thesurix** [comment]
I can not reproduce this behavior. I found that log **E/RecyclerView: No adapter attached; skipping layout** usually means that some operation is not executed on main thread (`notifyItemInserted()`, `notifyItemRemoved()` etc.) Could you reproduce this issue with one of the examples (maybe in `EmptyViewFragment.java`)? If not I will try to mess with Firebase environment.
